name: Backend Vulnerability Detection CI Pipeline

on:
  pull_request:
    branches: [ '**' ]
  schedule:
    - cron: "0 12 * * 6"

jobs:
  scan-image:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build an image from Dockerfile
        run: |
          docker build --pull --no-cache -t web-page-word-counter-node:${{ github.sha }} .
        working-directory: ./backend
      - name: Run Trivy vulnerability scanner on Docker image
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'web-page-word-counter-node:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
  scan-repo:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Trivy vulnerability scanner in fs mode
        run: |
          cd ./backend
          trivy fs . --format table --exit-code 1 --ignore-unfixed --vuln-type library --severity CRITICAL,HIGH
