name: Backend Linting and Testing CI Pipeline

on:
  pull_request:
    branches: [ '**' ]

jobs:
  lint-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
      working-directory: ./backend
    
    - run: npm run lint
      working-directory: ./backend
    
    - run: npm test
      working-directory: ./backend
